server:
  port: 9999

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false